'use strict';

/** @typedef {ioBroker.StringOrTranslated} StringOrTranslated */
/** @typedef {ioBroker.StateCommon} StateCommon */
/** @typedef {[id: string, type: "channel", name: StringOrTranslated]} DeviceChannelDefinition */
/** @typedef {StateCommon & { name: StringOrTranslated }} DeviceStateDefinition */

/**
 * @param {(text: string) => StringOrTranslated} t
 * @returns {DeviceChannelDefinition[]}
 */
function getDeviceChannelDefinitions(t) {
    return [
        ['info', 'channel', t('Info')],
        ['metrics', 'channel', t('Metrics')],
        ['metrics.error', 'channel', t('Error metrics')],
        ['metrics.map', 'channel', t('Map metrics')],
        ['metrics.mowing', 'channel', t('Mowing metrics')],
        ['metrics.pointMowing', 'channel', t('Point mowing metrics')],
        ['metrics.status', 'channel', t('Status metrics')],
        ['metrics.zones', 'channel', t('Zone metrics')],
        ['diagnostics', 'channel', t('Diagnostics')],
        ['diagnostics.features', 'channel', t('Feature diagnostics')],
        ['diagnostics.network', 'channel', t('Network diagnostics')],
        ['diagnostics.ota', 'channel', t('OTA diagnostics')],
        ['diagnostics.rtk', 'channel', t('RTK diagnostics')],
        ['diagnostics.security', 'channel', t('Security diagnostics')],
        ['diagnostics.system', 'channel', t('System diagnostics')],
        ['diagnostics.time', 'channel', t('Time diagnostics')],
        ['location', 'channel', t('Location')],
        ['location.gps', 'channel', t('GPS location')],
        ['location.pose', 'channel', t('Pose location')],
        ['location.charger', 'channel', t('Charger location')],
        ['map', 'channel', t('Map')],
        ['consumable', 'channel', t('Consumable')],
        ['consumable.blades', 'channel', t('Blades')],
        ['consumable.cameras', 'channel', t('Cameras')],
        ['consumable.chargingPort', 'channel', t('Charging port')],
        ['controls', 'channel', t('Controls')],
        ['controls.fullMapMowing', 'channel', t('Full-map mowing')],
        ['controls.nearChargerMowing', 'channel', t('Near-charger mowing')],
        ['controls.rain', 'channel', t('Rain controls')],
        ['controls.zoneMowing', 'channel', t('Zone mowing')],
        ['commands', 'channel', t('Commands')],
        ['commands.device', 'channel', t('Device commands')],
        ['commands.docking', 'channel', t('Docking commands')],
        ['commands.maintenance', 'channel', t('Maintenance commands')],
        ['commands.mowing', 'channel', t('Mowing commands')],
        ['zones', 'channel', t('Zones')],
        ['zones.manual', 'channel', t('Manual zones')],
        ['raw', 'channel', t('Raw')],
        ['raw.shadow', 'channel', t('Raw shadows')],
    ];
}

/**
 * @param {(text: string) => StringOrTranslated} t
 * @returns {Record<string, DeviceStateDefinition>}
 */
function getDeviceStateDefinitions(t) {
    return {
        'info.alias': { type: 'string', role: 'text', read: true, write: false, name: t('Alias') },
        'info.model': { type: 'string', role: 'text', read: true, write: false, name: t('Model') },
        'info.region': { type: 'string', role: 'text', read: true, write: false, name: t('Region') },
        'info.endpoint': {
            type: 'string',
            role: 'text',
            read: true,
            write: false,
            name: t('IoT endpoint'),
        },
        'map.image': {
            type: 'string',
            role: 'media.image',
            read: true,
            write: false,
            name: t('Full map image'),
        },
        'map.imageWithRtkMask': {
            type: 'string',
            role: 'media.image',
            read: true,
            write: false,
            name: t('Map image with RTK mask'),
        },
        'map.imageWithMowedPath': {
            type: 'string',
            role: 'media.image',
            read: true,
            write: false,
            name: t('Map image with mowed path'),
        },
        'info.online': {
            type: 'boolean',
            role: 'indicator.reachable',
            read: true,
            write: false,
            name: t('Online'),
        },
        'info.charging': {
            type: 'boolean',
            role: 'indicator.working',
            read: true,
            write: false,
            name: t('Charging'),
        },
        'info.lastServiceCommand': {
            type: 'string',
            role: 'text',
            read: true,
            write: false,
            name: t('Last service command'),
        },
        'info.lastPoll': { type: 'string', role: 'date', read: true, write: false, name: t('Last poll') },
        'consumable.chargingPort.life': {
            type: 'number',
            role: 'value',
            unit: '%',
            read: true,
            write: false,
            name: t('Charging port lifetime'),
        },
        'consumable.chargingPort.reset': {
            type: 'boolean',
            role: 'button',
            read: true,
            write: true,
            name: t('Reset charging port lifetime'),
            def: false,
        },
        'consumable.cameras.life': {
            type: 'number',
            role: 'value',
            unit: '%',
            read: true,
            write: false,
            name: t('Cameras lifetime'),
        },
        'consumable.cameras.reset': {
            type: 'boolean',
            role: 'button',
            read: true,
            write: true,
            name: t('Reset cameras lifetime'),
            def: false,
        },
        'consumable.blades.life': {
            type: 'number',
            role: 'value',
            unit: '%',
            read: true,
            write: false,
            name: t('Blades lifetime'),
        },
        'consumable.blades.reset': {
            type: 'boolean',
            role: 'button',
            read: true,
            write: true,
            name: t('Reset blades lifetime'),
            def: false,
        },
        'metrics.batteryLevel': {
            type: 'number',
            role: 'value.battery',
            unit: '%',
            read: true,
            write: false,
            name: t('Battery level'),
        },
        'metrics.status.mower': {
            type: 'string',
            role: 'text',
            read: true,
            write: false,
            name: t('Mower status'),
        },
        'metrics.status.robotRaw': {
            type: 'string',
            role: 'text',
            read: true,
            write: false,
            name: t('Raw robot status'),
        },
        'metrics.status.modeRaw': {
            type: 'string',
            role: 'text',
            read: true,
            write: false,
            name: t('Raw mode status'),
        },
        'metrics.mowing.time': {
            type: 'number',
            role: 'value.interval',
            unit: 's',
            read: true,
            write: false,
            name: t('Mowing time'),
        },
        'metrics.mowing.area': {
            type: 'number',
            role: 'value',
            unit: 'm²',
            read: true,
            write: false,
            name: t('Mowing area'),
        },
        'metrics.mowing.totalTime': {
            type: 'number',
            role: 'value.interval',
            unit: 's',
            read: true,
            write: false,
            name: t('Total mowing time'),
        },
        'metrics.mowing.totalArea': {
            type: 'number',
            role: 'value',
            unit: 'm²',
            read: true,
            write: false,
            name: t('Total mowing area'),
        },
        'metrics.mowing.borderActive': {
            type: 'boolean',
            role: 'indicator',
            read: true,
            write: false,
            name: t('Mowing border'),
        },
        'metrics.mowing.nearChargerActive': {
            type: 'boolean',
            role: 'indicator',
            read: true,
            write: false,
            name: t('Mowing nest'),
        },
        'metrics.mowing.fullYardActive': {
            type: 'boolean',
            role: 'indicator',
            read: true,
            write: false,
            name: t('Full-yard mowing enabled'),
        },
        'metrics.pointMowing.active': {
            type: 'boolean',
            role: 'indicator',
            read: true,
            write: false,
            name: t('Point mowing active'),
        },
        'metrics.pointMowing.x': {
            type: 'number',
            role: 'value',
            read: true,
            write: false,
            name: t('Point mowing X'),
        },
        'metrics.pointMowing.y': {
            type: 'number',
            role: 'value',
            read: true,
            write: false,
            name: t('Point mowing Y'),
        },
        'metrics.zones.manualCount': {
            type: 'number',
            role: 'value',
            read: true,
            write: false,
            name: t('Manual zone count'),
        },
        'metrics.zones.autoCount': {
            type: 'number',
            role: 'value',
            read: true,
            write: false,
            name: t('Auto zone count'),
        },
        'metrics.map.totalArea': {
            type: 'number',
            role: 'value',
            unit: 'm²',
            read: true,
            write: false,
            name: t('Total mapped area'),
        },
        'metrics.map.status': {
            type: 'string',
            role: 'text',
            read: true,
            write: false,
            name: t('Map status'),
        },
        'metrics.map.mappingTaskState': {
            type: 'string',
            role: 'text',
            read: true,
            write: false,
            name: t('Mapping task state'),
        },
        'metrics.error.code': {
            type: 'number',
            role: 'value',
            read: true,
            write: false,
            name: t('Error code'),
        },
        'metrics.error.description': {
            type: 'string',
            role: 'text',
            read: true,
            write: false,
            name: t('Error description'),
        },
        'metrics.error.active': {
            type: 'boolean',
            role: 'indicator.maintenance',
            read: true,
            write: false,
            name: t('Error active'),
        },
        'location.gps.latitude': {
            type: 'number',
            role: 'value.gps.latitude',
            read: true,
            write: false,
            name: t('GPS latitude'),
        },
        'location.gps.longitude': {
            type: 'number',
            role: 'value.gps.longitude',
            read: true,
            write: false,
            name: t('GPS longitude'),
        },
        'location.pose.x': {
            type: 'number',
            role: 'value',
            read: true,
            write: false,
            unit: 'm',
            name: t('Pose X'),
        },
        'location.pose.y': {
            type: 'number',
            role: 'value',
            read: true,
            write: false,
            unit: 'm',
            name: t('Pose Y'),
        },
        'location.pose.yaw': {
            type: 'number',
            role: 'value',
            read: true,
            write: false,
            name: t('Pose yaw'),
        },
        'location.pose.type': {
            type: 'string',
            role: 'text',
            read: true,
            write: false,
            name: t('Pose type'),
        },
        'location.charger.x': {
            type: 'number',
            role: 'value',
            read: true,
            write: false,
            unit: 'm',
            name: t('Charger X'),
        },
        'location.charger.y': {
            type: 'number',
            role: 'value',
            read: true,
            write: false,
            unit: 'm',
            name: t('Charger Y'),
        },
        'diagnostics.rtk.state': {
            type: 'string',
            role: 'text',
            read: true,
            write: false,
            name: t('RTK fix state'),
        },
        'diagnostics.rtk.baseState': {
            type: 'string',
            role: 'text',
            read: true,
            write: false,
            name: t('RTK base station state'),
        },
        'diagnostics.rtk.antennaMoved': {
            type: 'boolean',
            role: 'indicator',
            read: true,
            write: false,
            name: t('RTK antenna moved'),
        },
        'diagnostics.rtk.baseFirmware': {
            type: 'string',
            role: 'text',
            read: true,
            write: false,
            name: t('RTK base firmware'),
        },
        'diagnostics.cameraError': {
            type: 'boolean',
            role: 'indicator.maintenance',
            read: true,
            write: false,
            name: t('Camera error'),
        },
        'diagnostics.network.wifiConnected': {
            type: 'boolean',
            role: 'indicator.reachable',
            read: true,
            write: false,
            name: t('WiFi connected'),
        },
        'diagnostics.network.cellularConnected': {
            type: 'boolean',
            role: 'indicator.reachable',
            read: true,
            write: false,
            name: t('Cellular connected'),
        },
        'diagnostics.network.cellularHeartbeat': {
            type: 'boolean',
            role: 'indicator',
            read: true,
            write: false,
            name: t('Cellular heartbeat'),
        },
        'diagnostics.network.bluetoothActive': {
            type: 'boolean',
            role: 'indicator',
            read: true,
            write: false,
            name: t('Bluetooth active'),
        },
        'diagnostics.network.wifiSsid': {
            type: 'string',
            role: 'text',
            read: true,
            write: false,
            name: t('WiFi SSID'),
        },
        'diagnostics.network.ipAddress': {
            type: 'string',
            role: 'text',
            read: true,
            write: false,
            name: t('IP address'),
        },
        'diagnostics.network.simPresent': {
            type: 'boolean',
            role: 'indicator',
            read: true,
            write: false,
            name: t('SIM inserted'),
        },
        'diagnostics.network.simCcid': {
            type: 'string',
            role: 'text',
            read: true,
            write: false,
            name: t('SIM CCID'),
        },
        'diagnostics.mapAvailable': {
            type: 'boolean',
            role: 'indicator',
            read: true,
            write: false,
            name: t('Map available'),
        },
        'diagnostics.accelerometerActive': {
            type: 'boolean',
            role: 'indicator',
            read: true,
            write: false,
            name: t('Accelerometer active'),
        },
        'diagnostics.features.antiLossActive': {
            type: 'boolean',
            role: 'indicator',
            read: true,
            write: false,
            name: t('Anti-loss state'),
        },
        'diagnostics.features.edgeCutActive': {
            type: 'boolean',
            role: 'indicator',
            read: true,
            write: false,
            name: t('Edge-cut state'),
        },
        'diagnostics.features.indoorModeActive': {
            type: 'boolean',
            role: 'indicator',
            read: true,
            write: false,
            name: t('Indoor mode state'),
        },
        'diagnostics.features.autoUpgradeActive': {
            type: 'boolean',
            role: 'indicator',
            read: true,
            write: false,
            name: t('Auto upgrade state'),
        },
        'diagnostics.features.obstacleAvoidanceActive': {
            type: 'boolean',
            role: 'indicator',
            read: true,
            write: false,
            name: t('Obstacle avoidance state'),
        },
        'diagnostics.features.obstacleAvoidanceLevel': {
            type: 'number',
            role: 'value',
            read: true,
            write: false,
            name: t('Obstacle avoidance level'),
        },
        'diagnostics.features.drcActive': {
            type: 'boolean',
            role: 'indicator',
            read: true,
            write: false,
            name: t('DRC enabled'),
        },
        'diagnostics.features.logUploadActive': {
            type: 'boolean',
            role: 'indicator',
            read: true,
            write: false,
            name: t('Log upload enabled'),
        },
        'diagnostics.security.factoryResetPending': {
            type: 'boolean',
            role: 'indicator.maintenance',
            read: true,
            write: false,
            name: t('Factory reset pending'),
        },
        'diagnostics.security.unbindPending': {
            type: 'boolean',
            role: 'indicator',
            read: true,
            write: false,
            name: t('User unbind pending'),
        },
        'diagnostics.security.pinCode': {
            type: 'number',
            role: 'value',
            read: true,
            write: false,
            name: t('Device PIN'),
        },
        'diagnostics.security.antiLossRadius': {
            type: 'number',
            role: 'value',
            unit: 'm',
            read: true,
            write: false,
            name: t('Anti-loss radius'),
        },
        'diagnostics.system.eventCode': {
            type: 'number',
            role: 'value',
            read: true,
            write: false,
            name: t('Last event code'),
        },
        'diagnostics.system.firmwareVersion': {
            type: 'string',
            role: 'text',
            read: true,
            write: false,
            name: t('Firmware version'),
        },
        'diagnostics.system.mainBoardVersion': {
            type: 'string',
            role: 'text',
            read: true,
            write: false,
            name: t('Main board version'),
        },
        'diagnostics.system.extensionBoardVersion': {
            type: 'string',
            role: 'text',
            read: true,
            write: false,
            name: t('Extension board version'),
        },
        'diagnostics.system.protocolVersion': {
            type: 'string',
            role: 'text',
            read: true,
            write: false,
            name: t('Protocol version'),
        },
        'diagnostics.system.minimumAppVersion': {
            type: 'string',
            role: 'text',
            read: true,
            write: false,
            name: t('Minimum app version'),
        },
        'diagnostics.system.voiceLanguage': {
            type: 'string',
            role: 'text',
            read: true,
            write: false,
            name: t('Voice language'),
        },
        'diagnostics.ota.progress': {
            type: 'number',
            role: 'value',
            unit: '%',
            read: true,
            write: false,
            name: t('OTA progress'),
        },
        'diagnostics.ota.state': {
            type: 'string',
            role: 'text',
            read: true,
            write: false,
            name: t('OTA state'),
        },
        'diagnostics.ota.timeEstimate': {
            type: 'number',
            role: 'value.interval',
            unit: 's',
            read: true,
            write: false,
            name: t('OTA time estimate'),
        },
        'diagnostics.time.shadowUpdated': {
            type: 'string',
            role: 'date',
            read: true,
            write: false,
            name: t('Shadow last updated'),
        },
        'diagnostics.time.systemBoot': {
            type: 'string',
            role: 'date',
            read: true,
            write: false,
            name: t('System boot time'),
        },
        'diagnostics.time.mapUpdated': {
            type: 'string',
            role: 'date',
            read: true,
            write: false,
            name: t('Map last updated'),
        },
        'diagnostics.time.pathUpdated': {
            type: 'string',
            role: 'date',
            read: true,
            write: false,
            name: t('Path last updated'),
        },
        'diagnostics.time.areaUpdated': {
            type: 'string',
            role: 'date',
            read: true,
            write: false,
            name: t('Area last updated'),
        },
        'diagnostics.time.nextAppointment': {
            type: 'string',
            role: 'date',
            read: true,
            write: false,
            name: t('Next appointment'),
        },
        'controls.fullMapMowing.mowHeight': {
            type: 'number',
            role: 'level',
            unit: 'mm',
            min: 30,
            max: 70,
            read: true,
            write: true,
            name: t('Set full-map mow height'),
        },
        'controls.fullMapMowing.includeEdgeTrimming': {
            type: 'boolean',
            role: 'switch',
            read: true,
            write: true,
            name: t('Include edge trimming in full-map mowing'),
        },
        'controls.fullMapMowing.customMowingDirection': {
            type: 'number',
            role: 'level',
            unit: 'deg',
            min: 0,
            max: 180,
            read: true,
            write: true,
            name: t('Set full-map custom mowing direction'),
        },
        'controls.fullMapMowing.customMowingDirectionEnabled': {
            type: 'boolean',
            role: 'switch',
            read: true,
            write: true,
            name: t('Enable full-map custom mowing direction'),
        },
        'controls.zoneMowing.mowHeight': {
            type: 'number',
            role: 'level',
            unit: 'mm',
            min: 30,
            max: 70,
            read: true,
            write: true,
            name: t('Set zone mow height'),
        },
        'controls.zoneMowing.mowCount': {
            type: 'number',
            role: 'level',
            min: 1,
            max: 3,
            read: true,
            write: true,
            name: t('Set zone mow count'),
        },
        'controls.zoneMowing.customMowingDirection': {
            type: 'number',
            role: 'level',
            unit: 'deg',
            min: 0,
            max: 180,
            read: true,
            write: true,
            name: t('Set zone custom mowing direction'),
        },
        'controls.zoneMowing.customMowingDirectionEnabled': {
            type: 'boolean',
            role: 'switch',
            read: true,
            write: true,
            name: t('Enable zone custom mowing direction'),
        },
        'controls.zoneMowing.obstacleAvoidanceEnabled': {
            type: 'boolean',
            role: 'switch',
            read: true,
            write: true,
            name: t('Enable zone obstacle avoidance'),
        },
        'controls.zoneMowing.obstacleAvoidanceLevel': {
            type: 'number',
            role: 'level',
            min: 0,
            max: 2,
            read: true,
            write: true,
            name: t('Set zone obstacle avoidance level'),
        },
        'controls.voiceVolume': {
            type: 'number',
            role: 'level.volume',
            unit: '%',
            min: 0,
            max: 100,
            read: true,
            write: true,
            name: t('Set voice volume'),
        },
        'controls.rain.perceptionEnabled': {
            type: 'boolean',
            role: 'switch',
            read: true,
            write: true,
            name: t('Enable rain perception'),
        },
        'controls.rain.continueTimeHours': {
            type: 'number',
            role: 'level',
            unit: 'h',
            min: 0,
            max: 8,
            read: true,
            write: true,
            name: t('Set rain continue time'),
        },
        'controls.nearChargerMowing.enabled': {
            type: 'boolean',
            role: 'switch',
            read: true,
            write: true,
            name: t('Enable mowing near charging pile'),
        },
        'controls.nearChargerMowing.mowHeight': {
            type: 'number',
            role: 'level',
            unit: 'mm',
            min: 30,
            max: 70,
            read: true,
            write: true,
            name: t('Set near charger mow height'),
        },
        'controls.nearChargerMowing.mowCount': {
            type: 'number',
            role: 'level',
            min: 1,
            max: 3,
            read: true,
            write: true,
            name: t('Set near charger mow count'),
        },
        'controls.nearChargerMowing.obstacleAvoidanceEnabled': {
            type: 'boolean',
            role: 'switch',
            read: true,
            write: true,
            name: t('Enable near charger obstacle avoidance'),
        },
        'controls.nearChargerMowing.obstacleAvoidanceLevel': {
            type: 'number',
            role: 'level',
            min: 0,
            max: 2,
            read: true,
            write: true,
            name: t('Set near charger obstacle avoidance level'),
        },
        'commands.device.find': {
            type: 'boolean',
            role: 'button',
            read: true,
            write: true,
            name: t('Find robot'),
            def: false,
        },
        'commands.device.refresh': {
            type: 'boolean',
            role: 'button',
            read: true,
            write: true,
            name: t('Request refresh'),
            def: false,
        },
        'commands.device.cancelRtkAntennaMoved': {
            type: 'boolean',
            role: 'button',
            read: true,
            write: true,
            name: t('Cancel RTK antenna moved warning'),
            def: false,
        },
        'commands.docking.startReturn': {
            type: 'boolean',
            role: 'button',
            read: true,
            write: true,
            name: t('Return to dock'),
            def: false,
        },
        'commands.docking.pauseReturn': {
            type: 'boolean',
            role: 'button',
            read: true,
            write: true,
            name: t('Pause return to dock'),
            def: false,
        },
        'commands.maintenance.startGrassDump': {
            type: 'boolean',
            role: 'button',
            read: true,
            write: true,
            name: t('Start grass dump'),
            def: false,
        },
        'commands.maintenance.startDiskMaintenance': {
            type: 'boolean',
            role: 'button',
            read: true,
            write: true,
            name: t('Start disk maintenance mode'),
            def: false,
        },
        'commands.mowing.startFullMap': {
            type: 'boolean',
            role: 'button',
            read: true,
            write: true,
            name: t('Start full-map mow'),
            def: false,
        },
        'commands.mowing.startZone': {
            type: 'string',
            role: 'text',
            read: true,
            write: true,
            name: t('Start manual zone mow'),
        },
        'commands.mowing.startAutoZone': {
            type: 'string',
            role: 'text',
            read: true,
            write: true,
            name: t('Start auto zone mow'),
        },
        'commands.mowing.startPoint': {
            type: 'string',
            role: 'text',
            read: true,
            write: true,
            name: t('Start point mow'),
        },
        'commands.mowing.startEdge': {
            type: 'boolean',
            role: 'button',
            read: true,
            write: true,
            name: t('Start edge mow'),
            def: false,
        },
        'commands.mowing.startNearCharger': {
            type: 'boolean',
            role: 'button',
            read: true,
            write: true,
            name: t('Start mowing near charging pile'),
            def: false,
        },
        'commands.mowing.pause': {
            type: 'boolean',
            role: 'button',
            read: true,
            write: true,
            name: t('Pause mowing'),
            def: false,
        },
        'commands.mowing.resume': {
            type: 'boolean',
            role: 'button',
            read: true,
            write: true,
            name: t('Resume mowing'),
            def: false,
        },
        'commands.mowing.stop': {
            type: 'boolean',
            role: 'button',
            read: true,
            write: true,
            name: t('Stop mow'),
            def: false,
        },
        'commands.mowing.end': {
            type: 'boolean',
            role: 'button',
            read: true,
            write: true,
            name: t('End mowing'),
            def: false,
        },
        'commands.mowing.stopPoint': {
            type: 'boolean',
            role: 'button',
            read: true,
            write: true,
            name: t('Stop point mow'),
            def: false,
        },
        'zones.manual.list': {
            type: 'string',
            role: 'json',
            read: true,
            write: false,
            name: t('Manual zones'),
        },
        'zones.manual.activeIds': {
            type: 'string',
            role: 'json',
            read: true,
            write: false,
            name: t('Active manual zone IDs'),
        },
        'zones.autoList': {
            type: 'string',
            role: 'json',
            read: true,
            write: false,
            name: t('Auto zones'),
        },
        'raw.shadow.property': {
            type: 'string',
            role: 'json',
            read: true,
            write: false,
            name: t('Raw property shadow'),
        },
        'raw.shadow.service': {
            type: 'string',
            role: 'json',
            read: true,
            write: false,
            name: t('Raw service shadow'),
        },
        'raw.shadow.event-code': {
            type: 'string',
            role: 'json',
            read: true,
            write: false,
            name: t('Raw event code translations'),
        },
        'raw.areaDefinition': {
            type: 'string',
            role: 'json',
            read: true,
            write: false,
            name: t('Raw area definition'),
        },
    };
}

const BOOLEAN_COMMANDS = [
    'device.find',
    'device.refresh',
    'device.cancelRtkAntennaMoved',
    'docking.startReturn',
    'docking.pauseReturn',
    'maintenance.startGrassDump',
    'maintenance.startDiskMaintenance',
    'mowing.startFullMap',
    'mowing.startEdge',
    'mowing.startNearCharger',
    'mowing.pause',
    'mowing.resume',
    'mowing.stop',
    'mowing.end',
    'mowing.stopPoint',
];

const STRING_COMMANDS = ['mowing.startZone', 'mowing.startAutoZone', 'mowing.startPoint'];

const MAINTENANCE_RESET_TYPES = {
    'blades.reset': 0,
    'cameras.reset': 1,
    'chargingPort.reset': 2,
};

module.exports = {
    BOOLEAN_COMMANDS,
    MAINTENANCE_RESET_TYPES,
    STRING_COMMANDS,
    getDeviceChannelDefinitions,
    getDeviceStateDefinitions,
};
